---
- hosts: fcos
  gather_facts: false
  become: yes

  vars_files:
    - external_vars.yml

  tasks:

    - name: STRG-1846 - Check if firewire storage is disabled
      copy:
        dest: /etc/modprobe.d/firewire.conf
        content: |
          blacklist firewire-core
      tags:
        - STRG-1846
