---
- hosts: fcos
  gather_facts: false

  vars:
    ansible_python_interpreter: '/usr/bin/python3'

  tasks:

    - name: Disable service debug-shell
      become: yes
      systemd:
        name: debug-shell.service
        enabled: no
        state: stopped
        masked: yes
      tags:
        - service_debug-shell_disabled
        - medium_severity
        - disable_strategy
        - low_complexity
        - low_disruption
        - no_reboot_needed
        - CCE-82496-1
        - NIST-800-171-3.4.5

    - name: Get local hostname.
      uri:
        url: http://169.254.169.254/latest/meta-data/local-hostname
        return_content: yes
      register: localhostname

    - name: Set local hostname. Use hostnamectl to confirm static hostname.
      become: yes
      hostname:
        name: "{{localhostname.content}}"
