---
- hosts: fcos
  gather_facts: false

  vars_files:
    - external_vars.yml

  tasks:

    - name: Get local hostname.
      uri:
        url: http://169.254.169.254/latest/meta-data/local-hostname
        return_content: yes
      register: localhostname

    - name: Set local hostname. Use hostnamectl to confirm static hostname.
      become: yes
      hostname:
        name: "{{localhostname.content}}"
