---
- hosts: fcos
  gather_facts: false

  vars_files:
    - external_vars.yml

  tasks:

    #
    # I'll be terminating images instead of auto-updating. Also 
    # my servers might not have access to the Internet.
    #
    - name: Stop and Disable Zincati auto-updating
      become: yes
      systemd:
        enabled: no
        masked: yes
        name: zincati
        state: stopped

    - name: Disable service debug-shell
      become: yes
      systemd:
        enabled: no
        masked: yes
        name: debug-shell.service
        state: stopped
      tags:
        - service_debug-shell_disabled
        - medium_severity
        - disable_strategy
        - low_complexity
        - low_disruption
        - no_reboot_needed
        - CCE-82496-1
        - NIST-800-171-3.4.5

    - name: Get local hostname.
      uri:
        url: http://169.254.169.254/latest/meta-data/local-hostname
        return_content: yes
      register: localhostname

    - name: Set local hostname. Use hostnamectl to confirm static hostname.
      become: yes
      hostname:
        name: "{{localhostname.content}}"
